
package com.negeso.framework.module.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CentralModulesProvider", targetNamespace = "http://ws.module.framework.negeso.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CentralModulesProvider {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.negeso.framework.module.ws.CentralModule>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModules", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.GetModules")
    @ResponseWrapper(localName = "getModulesResponse", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.GetModulesResponse")
    public List<CentralModule> getModules(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "resetCache", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.ResetCache")
    @ResponseWrapper(localName = "resetCacheResponse", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.ResetCacheResponse")
    public void resetCache();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.negeso.framework.module.ws.CentralModule>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllModules", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.GetAllModules")
    @ResponseWrapper(localName = "getAllModulesResponse", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.GetAllModulesResponse")
    public List<CentralModule> getAllModules(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isModuleEnabled", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.IsModuleEnabled")
    @ResponseWrapper(localName = "isModuleEnabledResponse", targetNamespace = "http://ws.module.framework.negeso.com/", className = "com.negeso.framework.module.ws.IsModuleEnabledResponse")
    public boolean isModuleEnabled(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
